### ISSUE TITLE
Enemy is referred to as Hordies when playing as Horde

### ISSUE THREAD

**Issue by mfolio2** [The-Sickness/IncCallout#1]
Temporary fixes:
local function ButtonOnClick(self)
    if not isInBattleground() then
        print("You are not in a battleground.")
        return
    end

    local currentLocation = GetSubZoneText()
    local enemyFaction = playerFaction == "enemy" and "enemy" or "enemy"
    local message = self:GetText() .. " " .. enemyFaction .. " incoming at " .. currentLocation
    SendChatMessage(message, "INSTANCE_CHAT")
end

**Comment by The-Sickness** [comment]
Ok. I didn't know about that one seeing I don't play Horde. I will fix this asap. Thank you for the heads up.

**Comment by The-Sickness** [comment]
Code has been fixed
