### ISSUE TITLE
Other players are complaining about the full zone being printed in an incoming call out.

### ISSUE THREAD

**Issue by mfolio2** [The-Sickness/IncCallout#2]
Temporary fixes-- 
remove GetRealZoneText() from functions :

local function AllClearButtonOnClick()
    local location = GetSubZoneText()

    -- Check if location is in the defined battleground locations
    if not location then
        print("You are not in a BattleGround.")
        return
    end

    local message = buttonMessages.allClear[buttonMessageIndices.allClear] .. " at " .. location
    SendChatMessage(message, "INSTANCE_CHAT")
end
allClearButton:SetScript("OnClick", AllClearButtonOnClick)

-- Function to handle the Send More button click event
local function SendMoreButtonOnClick()
    local location = GetSubZoneText()

    -- Check if location is in the defined battleground locations
    if not location then
        print("You are not in a BattleGround.")
        return
    end

    local message = buttonMessages.sendMore[buttonMessageIndices.sendMore] .. " at " .. location
    SendChatMessage(message, "INSTANCE_CHAT")
end
sendMoreButton:SetScript("OnClick", SendMoreButtonOnClick)

-- Function to handle the INC button click event
local function IncButtonOnClick()
    local location = GetSubZoneText()

    -- Check if location is in the defined battleground locations
    if not location then
        print("You are not in a BattleGround.")
        return
    end

    local message = buttonMessages.inc[buttonMessageIndices.inc] .. " at " .. location
    SendChatMessage(message, "INSTANCE_CHAT")
end
incButton:SetScript("OnClick", IncButtonOnClick)

-- Register the slash command
SLASH_INC1 = "/inc"
SlashCmdList["INC"] = function()
    if IncCallout:IsShown() then
        IncCallout:Hide()
    end
end

**Comment by The-Sickness** [comment]
What do you mean the "full zone"?

**Comment by The-Sickness** [comment]
Code has been fixed
