### ISSUE TITLE
Alliance merced as Horde mix up

### ISSUE THREAD

**Issue by mfolio2** [The-Sickness/IncCallout#3]
When playing Alliance merced as Horde, it outs me as an Alliance merc.  In IOC, if I do a call out, it identifies my own team (as a merc) as the incoming.

**Comment by The-Sickness** [comment]
Ok, I'll take a look and see about fixing that.

**Comment by The-Sickness** [comment]
Can you tell me if this happens if you use the buttons 1-4 and Zerg?

**Comment by The-Sickness** [comment]
Open the IncCallout.lua, look for this: 
local function ButtonOnClick(self)
    local currentLocation = GetSubZoneText()
    local playerFaction = UnitFactionGroup("player") or ""
    local enemyFaction = playerFaction == "Alliance" and "Horde" or "Alliance"
    local message = self:GetText() .. " " .. enemyFaction .. " incoming at " .. currentLocation
    SendChatMessage(message, "INSTANCE_CHAT")
end

Change it to this: 
local function ButtonOnClick(self)
    local currentLocation = GetSubZoneText()
    local playerTeamColor = GetPlayerRaidColor() -- This is a hypothetical function; implement the logic to determine player's current team based on raid/party color
    local playerFaction = playerTeamColor == "green" and "Horde" or "Alliance" -- Adjust based on how you determine the team
    local message = self:GetText() .. " " .. playerFaction .. " incoming at " .. currentLocation
    SendChatMessage(message, "INSTANCE_CHAT")
end

Please let me know if this fixes the issue. I don't have time to play do to work.
